properties(
    [
        pipelineTriggers(
            [githubPush()]
        )
    ]
)

node {
    stage('Git pull') {
        dir('/home/ec2-user/Crypto-Forecaster-gas') {
            sh('git pull')
        }
    }
}